application: flowstaging
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /admin/?.*
  script: main.py
  login: required

- url: /npo/[^/]+/admin/?.*
  script: main.py
  login: required

- url: /cron/.*
  script: main.py
  login: admin
  
  
- url: /.*
  script: main.py
