from django.http import HttpResponse
from django.shortcuts import render_to_response
from django.template import TemplateDoesNotExist

showArtPages = [ 
                {'filename'    : 'base.html', 
                 'name'        : 'Base Page', 
                 'description' : 'The base of HTML page',
                 'owner'       : 'brian_wang', 
                 'status'      : 'DONE'},
                {'filename'    : 'splashbox.html', 
                 'name'        : 'Splash Box', 
                 'description' : 'included by xxx Base Page',
                 'owner'       : 'brian_wang', 
                 'status'      : 'DONE'},
                {'filename'    : 'splashbox_search.html', 
                 'name'        : 'Splash Box - Search Version', 
                 'description' : 'included by xxx Base Page',
                 'owner'       : 'tom_chen', 
                 'status'      : 'DONE'},
                {'filename'    : 'twocolumn_base.html', 
                 'name'        : 'Two Column: Base Page', 
                 'description' : 'two column layout template, extends Base Page',
                 'owner'       : 'tom_chen', 
                 'status'      : 'DONE'},
                {'filename'    : 'profile_base.html', 
                 'name'        : 'Profile: Base Page', 
                 'description' : 'extends Two Column Base Page',
                 'owner'       : 'tom_chen', 
                 'status'      : 'DONE'},
                {'filename'    : 'profile_leftcolumn.html', 
                 'name'        : 'Profile: Sidebar', 
                 'description' : 'sidebar content, included by Profile Base Page',
                 'owner'       : 'tom_chen', 
                 'status'      : 'PARTIAL'},
                {'filename'    : 'profile_content.html', 
                 'name'        : 'Profile: Sample Content',
                 'description' : 'sample content, extends Profile Base Page', 
                 'owner'       : 'tom_chen', 
                 'status'      : 'DONE'},
                {'filename'    : 'registration/base.html', 
                 'name'        : 'Registration: Base Page',
                 'description' : 'extends Base Page', 
                 'owner'       : 'tom_chen', 
                 'status'      : 'TODO'},
                {'filename'    : 'registration/user_step1.html', 
                 'name'        : 'Registration: User Registration Step 1 Page',
                 'description' : 'extends Registration Base Page', 
                 'owner'       : 'tom_chen', 
                 'status'      : 'DONE'},
                {'filename'    : 'registration/user_step2.html', 
                 'name'        : 'Registration: User Registration Step 2 Page',
                 'description' : 'extends Registration Base Page', 
                 'owner'       : 'tom_chen', 
                 'status'      : 'DONE'},
                {'filename'    : 'registration/user_step3.html', 
                 'name'        : 'Registration: User Registration Step 3 Page',
                 'description' : 'extends Registration Base Page', 
                 'owner'       : 'tom_chen', 
                 'status'      : 'DONE'},
                {'filename'    : 'registration/npo_step1.html', 
                 'name'        : 'Registration: NPO Registration Step 1 Page',
                 'description' : 'extends Registration Base Page', 
                 'owner'       : 'tom_chen', 
                 'status'      : 'DONE'},
                {'filename'    : 'registration/npo_step2.html', 
                 'name'        : 'Registration: NPO Registration Step 2 Page',
                 'description' : 'extends Registration Base Page', 
                 'owner'       : 'tom_chen', 
                 'status'      : 'DONE'},
                {'filename'    : 'registration/npo_step3.html', 
                 'name'        : 'Registration: NPO Registration Step 3 Page',
                 'description' : 'extends Registration Base Page', 
                 'owner'       : 'tom_chen', 
                 'status'      : 'DONE'},
                {'filename'    : 'activity/activity-list.html', 
                 'name'        : 'Activity: Activity List',
                 'description' : 'extends Activity Base Page', 
                 'owner'       : 'brian_wang', 
                 'status'      : 'DONE'},
                {'filename'    : 'activity/activity-info.html', 
                 'name'        : 'Activity: Activity Info',
                 'description' : 'extends Activity Base Page', 
                 'owner'       : 'brian_wang', 
                 'status'      : 'DONE'},
                {'filename'    : 'activity/activity-info-header.html', 
                 'name'        : 'Activity: Activity Info Header',
                 'description' : 'included by Activity Info & Apply page', 
                 'owner'       : 'brian_wang', 
                 'status'      : 'DONE'},
                {'filename'    : 'activity/activity-info-basic.html', 
                 'name'        : 'Activity: Activity Basic Info',
                 'description' : 'included by Activity Info & Apply page', 
                 'owner'       : 'brian_wang', 
                 'status'      : 'DONE'},
                {'filename'    : 'activity/activity-apply.html', 
                 'name'        : 'Activity: Activity Application',
                 'description' : 'extends Activity Base Page', 
                 'owner'       : 'brian_wang', 
                 'status'      : 'DONE'},
                {'filename'    : 'activity/activity-admin-list.html', 
                 'name'        : 'Activity: Admin Activity List',
                 'description' : 'extends Activity Base Page', 
                 'owner'       : 'feynman_huang', 
                 'status'      : 'DONE'},
                {'filename'    : 'activity/activity-admin-add.html', 
                 'name'        : 'Activity: Admin Add Activity',
                 'description' : 'extends Activity Base Page', 
                 'owner'       : 'feynman_huang', 
                 'status'      : 'DONE'},
                {'filename'    : 'activity/activity-admin-edit.html', 
                 'name'        : 'Activity: Admin Edit Activity',
                 'description' : 'extends Activity Base Page', 
                 'owner'       : 'feynman_huang', 
                 'status'      : 'DONE'},
                {'filename'    : 'activity/activity-admin-cancel.html', 
                 'name'        : 'Activity: Admin Cancel Activity',
                 'description' : 'extends Activity Base Page', 
                 'owner'       : 'camgelo', 
                 'status'      : 'DONE'},
                {'filename'    : 'activity/activity-admin-validate.html', 
                 'name'        : 'Activity: Admin Validate Activity Volunteers',
                 'description' : 'extends Activity Base Page', 
                 'owner'       : 'tom_chen/brian_wang', 
                 'status'      : 'PARTIAL'},
                ]

def showartAction(request, filename):
    if ('' == filename):
        return render_to_response('showart.html', {'showart_pages' : showArtPages})
    else:
        try:
            response = render_to_response(filename, {})
        except TemplateDoesNotExist:
            response = HttpResponse('Page not found or included / extended template not found: '+filename)
        return response
